baseURL: "https://joshaustin.tech/"
languageCode: "en-us"
title: "Josh Austin"
theme: "PaperMod"

menu:
  main:
    - name: Home
      url: "/"
      weight: 1
    - name: Posts
      url: "/blog"
      weight: 2
    - name: Search
      url: "/search/"
      weight: 3
    - name: Tags
      url: "/tags/"
      weight: 4

permalinks:
  page:
    posts: /blog/:slug/
  section:
    posts: /blog/

params:
  defaultTheme: auto
  env: production

  profileMode:
    subtitle: Java and Swift developer consultant
    enabled: true
    imageUrl: "images/431100755_388523090475232_1555015838056185344_n.jpg" # optional
    imageTitle: "profile picture of Josh Austin in the car wearing sunglasses"
    imageWidth: 256 # custom size
    imageHeight: 256 # custom size

  socialIcons:
  - name: github
    url: "https://github.com/joshaustintech"
  - name: threads
    url: "https://threads.net/@joshaustin.tech"
  - name: mastodon
    url: "https://foojay.social/@josh"
  - name: linkedin
    url: "https://linkedin.com/in/joshaustintech"
  - name: rss
    url: "/index.xml"
outputs:
  home:
    - HTML
    - RSS
    - JSON
