baseURL: "https://joshaustin.tech/"
languageCode: "en-us"
title: "Josh Austin"
theme: "PaperMod"

menu:
  main:
    - name: Home
      url: "/"
      weight: 1
    - name: Posts
      url: "/blog"
      weight: 2
    - name: Search
      url: "/search/"
      weight: 3
    - name: Tags
      url: "/tags/"
      weight: 4

permalinks:
  page:
    posts: /blog/:slug/
  section:
    posts: /blog/

params:
  defaultTheme: auto
  env: production

  profileMode:
    subtitle: ðŸ’Ž Rails Matchmaker Â· I deliver proven US Ruby Engineers Â· ChicagoRuby Co-Organizer
    enabled: true
    imageUrl: "images/square_profile_image.png"
    imageTitle: "AI headshot of Josh in downtown Chicago"
    imageWidth: 256
    imageHeight: 256
    buttons:
    - name: Book a Call ($20 USD)
      url: "https://calendly.com/joshaustintech/30-minute-meeting"
    - name: Book a Job Search Booster (US Citizens & Green Card Only) ($300 USD)
      url: "https://calendly.com/joshaustintech/interview-prep"
  socialIcons:
  - name: github
    url: "https://github.com/joshaustintech"
  - name: linkedin
    url: "https://linkedin.com/in/joshaustintech"
  - name: youtube
    url: "https://youtube.com/@ObjectSanctuary"
  - name: rss
    url: "/index.xml"
outputs:
  home:
    - HTML
    - RSS
    - JSON
